### ISSUE TITLE
OpenJS Foundation Executive Director Job Description

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/bootstrap#151]
Hey all,

A subcommittee of the board has been working on a job description for the executive director position. Below is a link to a Google doc with the current draft.

It would be great if people could give feedback and we could discuss as a group during Monday's call.

https://docs.google.com/document/d/1uLNZkJyEO9OgzIIzT5peTkqSaUoM-0QRIw1Wc9LAJPA/edit

**Comment by brianwarner** [comment]
We realized after the fact that sharing is not open on this version.  Here's a new version that should be accessible to everyone with the link:
https://docs.google.com/document/d/1uLNZkJyEO9OgzIIzT5peTkqSaUoM-0QRIw1Wc9LAJPA/edit

**Comment by mhdawson** [comment]
Overall it looks pretty good to me. One thing I'd like to see added is a section along these lines in terms of the responsibilities:

Support the member projects

1. Ensure projects have the resources they need to carry out the required day to day activities including infrastructure, tooling (like zoom) etc.
2. Ensure Foundation contacts and available resources are clearly documented and easily accessible by project members.
3. Ensure there is a framework and resources in place help projects manage CoC issues.
4. Act as a bridge between the CPC, member projects and the Board

I think that will help make it clear that one of the responsibilities is supporting the projects getting their work done in addition to evangelization.

**Comment by mcollina** [comment]
I don’t see requirements on locations, timezones, etc. Is there an expectation for the ED to be a US resident?

**Comment by bnb** [comment]
Putting all my notes here.

1. I'm not sure if defining a specific number is... resilient. That number could go up or down before the role is finalized.

Original:
> The OpenJS Foundation is made up of 31 open source

Suggestion:
> The OpenJS Foundation is made up of dozens of open-source

2. Is the word "JavaScript" intentionally left out? Outside of the Foundation – meaning in the community and ecosystem – I've never seen "JS" used in the place of "JavaScript" as extensively as it is here.

3. There's a part about ECMA:

>creating affiliations and maintaining good working relationships with organizations such as ECMA

I believe the proper name is ECMA International?

4. The line... 

>Identify potential new projects, working alongside Foundation members, the CPC, and the community.

... is extremely vague, and I'm not sure if it's actually descriptive of the intent behind it. All the other bullets in this section are very well fleshed out, but this one is comparatively bare. Perhaps more context could be added to this line to better define the expectation/intent behind it? Happy to help with that wordsmithing with others if I can better understand the context.

5. The line...

>Direct a multi-disciplinary team to build strong project brands that engage end users and demonstrate the benefits of adopting JS technologies.

...is concerning to me. I know the intent isn't that the ED and the Linux Foundation will "own" the various brands and images of the OSS projects (that's how I'd feel if I was assuming bad faith) but that _is_ how this reads to me. Is there nuance here that I'm missing?

6. The line...

> Take an active role in ensuring that renewing members understand the value of continued membership, communicating achievements and progress on a regular basis.

... seems to be indicative of a one-way conversation. "This is valuable." I'd also like to see an amendment to this that pushes for _increasing_ that value: 

>> Take an active role in ensuring that renewing members understand the value of continued membership, by communicating achievements and progress on a regular basis, and finding new avenues to increase the value of membership.

My perspective on this is that telling people something is valuable lets them fall off if they don't have the same definition of "value" as you do. Working with members to ensure they're _getting_ value (rather than being told there _is_ value) is important IMO.

**Comment by bnb** [comment]
Also, I wanted to add that I deeply appreciate this being the first requirement:

> Strong technical understanding of JS and related technologies, and experience building open source communities.

**Comment by bnb** [comment]
Additionally, I'd like to see if we can strike this requirement as it currently stands in favor of a more inclusive approach:

> Required: B.A. or B.S degree or comparable industry experience.

**Comment by gdams** [comment]
> Required: B.A. or B.S degree or comparable industry experience.

@bnb how about we change it to be `Recommended` ?

**Comment by ljharb** [comment]
Why is it recommended? What value does it add?

**Comment by brianwarner** [comment]
Thank you everyone for your input so far.  I believe the current draft reflects the comments and discussion in the bootstrap call.  Can everyone please have one more look at the draft?  If it looks good, I'd like to get this prepared for posting in the next day or so.

**Comment by bnb** [comment]
@brianwarner could we address the comment above (https://github.com/openjs-foundation/bootstrap/issues/151#issuecomment-480403271) that we weren't able to get to in the meeting? 🙏

**Comment by mcollina** [comment]
@brianwarner I do not see an answer about my comment

> I don’t see requirements on locations, timezones, etc. Is there an expectation for the ED to be a US resident?

It would be good to have a sentence about it.

**Comment by brianwarner** [comment]
@mcollina, here's what is currently in the draft: "Location is virtual but will require being available during US timezone working hours to coordinate with other staff working on the project."

In the meeting, we discussed that virtual means there's no US residency requirement.  Does that address your concern?

**Comment by brianwarner** [comment]
@bnb I believe we discussed changing it to "recommended" instead of "required", per what's in the current draft.  But that said, I don't think there was a strong feeling about keeping it.  Thoughts?

**Comment by mcollina** [comment]
@brianwarner I cannot find that sentence on the draft linked at the top of this page.

**Comment by brianwarner** [comment]
Oh, hang on, I see the issue.  Suggested changes don't appear in "view-only" mode, and I thought they did.  My mistake, I'll accept the changes and then you should be able to find it.
